### ISSUE TITLE
mprserv_121.ico missing

### ISSUE THREAD

**Issue by deckenventilator24** [erfg12/WinXP_Theme#1]
mprserv_121.ico, conf_148.ico, confcp_116.ico are not found in System Icons folder

**Comment by erfg12** [comment]
I modified the readme to replace those with the newer png options. Those were the icons for the Windows 9x theme package.
https://github.com/erfg12/WinXP_Theme/commit/bc385f421bfcc2795616d0f205158de772c2705a
