### ISSUE TITLE
ADD: Screensaver

### ISSUE THREAD

**Issue by deckenventilator24** [erfg12/WinXP_Theme#2]
I think you have one missing screensaver. The default one from Windows XP called logon.scr found in system32 on Windows XP machines. I've got it from a 64 bit XP VM and it's running perfectly fine. Would be nice if you could grab it from a VM and add it to this repository for others. In case of not beeing able to get it here's a link of the file uploaded to mediafire (by me).

http://www.mediafire.com/file/606salpdtkqxmtb/logon.scr/file

**Comment by erfg12** [comment]
added
